#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'rbenv', :git => 'git://github.com/fnichol/chef-rbenv.git', :ref => 'v0.7.2'
cookbook 'ruby_build'
cookbook 'build-essential', :git => 'git@github.com:opscode-cookbooks/build-essential.git', :ref => 'v1.4.4'
cookbook 'sqlite'
